---
# rke2_configure_private_registries/tasks/main.yml

- name: 'Create the registries.yaml file'
  ansible.builtin.template:
    src: 'registries.yaml.j2'
    dest: '/etc/rancher/rke2/registries.yaml'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
    - 'Restart the rke2 service on a server'
    - 'Restart the rke2 service on an agent'
